[project]
name = "disaster-pulse-etl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aravindp14", email = "aravindp14@gmail.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "boto3>=1.43.81",
    "pandas>=3.0.5",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
disaster-pulse-etl = "disaster_pulse_etl:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
